---
- name: Include downloader role
  ansible.builtin.import_role:
    name: mirceanton.downloader
  vars:
    downloader_archive_url: "{{ packer_url }}"
    downloader_archive_dest: "{{ packer_temp_download_dir }}"
    downloader_exec_src: "{{ packer_temp_download_dir }}/packer"
    downloader_exec_dest: "{{ packer_exec_path }}"
