---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  gather_facts: true

  vars_files:
    - ../../defaults/main.yml
    - ../../vars/main.yml

  tasks:
    - name: Try running packer
      ansible.builtin.command: "packer --version"
      register: __command__
      changed_when: false

    - name: Check command output
      ansible.builtin.assert:
        that:
          - __command__.rc == 0
          - packer_version in __command__.stdout
